BedrockStreaming/tech.bedrockstreaming.com

_posts/2016-01-26-m6web-lyon-recherche-developpeur-player-video-web-h-f-en-cdi.md

C'est une annonce en français, donc utiliser des termes en français, c'est mieux, non ? Autant "streaming"ce n'est pas forcément évident à traduire, autant "player", quand même ...

Remplacement des anglicismes exagérés

---

_posts/2017-03-30-prettier.md

Because Windows doesn't do well with single quotes

use escaped double quotes for format script

---

_posts/2017-03-30-prettier.md

M6Web eslint config is not public, so it could not be linked in the article
close #169

Remove eslint link in prettier article

---

.travis.yml

Surge servait à faire une preview du blog avant publication, mais l'intégration n'a jamais très bien marché. Je préfère supprimer ceci (qui en plus casse régulièrement l'inté continue) en attendant de remettre en place quelque chose de mieux.

Delete surge from CI

---

_posts/2017-06-01-migration-elasticsearch.md

> En passant, si vous avez trouvé une faute de frappe, vous pouvez forker et éditer ce post. Merci beaucoup !
s/puis reccomencer!/puis recommencer !

fix typo in elasticsearch migration post

---

_config.yml

After merging my previous PR, GitHub Pages sent me an email:
> The page build completed successfully, but returned the following warning for the `master` branch:
You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml' and ensure the 'pygments' key is unset. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.
> For information on troubleshooting Jekyll see:
https://help.github.com/articles/troubleshooting-jekyll-builds
https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors

Fixing highlighting errors (pygments to rouge)

---

oss.md

Recently I added the SVG sprite feature on 6play.
When I wanted to add it in our project, I found out there was a missing feature.
I took some time to push implementation of that feature and maintainer accepted it.

add contribution to OSS project

---

.github/workflows/integration.yml
.travis.yml

Travis-ci free tier is very slow now and with a lot of queuing. Github Action is a great and simple alternative.
- add simple CI workflow
- remove travis workflow

chore(ci): prefer github action instead of travis-ci

---

_posts/2021-11-18-hsdo.md
_posts/2021-12-15-scaling-bedrock-video-delivery-to-50-million-users.md
_posts/2022-03-08-cloudfront-web-streaming-platform-part-1.md

Following the set up of the new theme for Bedrock tech blog site, some HTML links are dead.

fix(url): update html links to our colleagues' blog posts

---

Gemfile
Gemfile.lock
_config.yml
_sass/layouts/_posts.scss

add [jekyll-figure](https://www.rubydoc.info/gems/jekyll-figure/0.1.0) Gem that can generate figure element with this syntax : 
```
{% figure caption:"Rejoignez-nos équipes et venez vivre les prochaines conférences avec nous l’an prochain" class:"figure" %}
{% endfigure %}
```
create a css content associated to the `figure` class for a better render :

feat: add figure and figcaption element

---

Gemfile
Gemfile.lock
_config.yml
_sass/layouts/_posts.scss

Reverts BedrockStreaming/tech.bedrockstreaming.com#324
`jekill-figure` plugin isn't supported by github-pages :( 
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins

Revert "feat: add figure and figcaption element"

---

_includes/default/tags_list.liquid

Fix #313 
Link for post are now functional :)

fix: use correct link for tags in post

---

_layouts/video-list.liquid

Enhance display of video cards in lft and meetups pages:
- display title in 2 lines
- cards now use full space available
- author is visible
- date is now visible
- tags display on 2 lines
- use bigger gap for readability

feat: enhance display of video cards

---

CONTRIBUTING.md

Many people forgot to put the `conference` tag in their video sharing articles.
This PR enhance the doc to make it more visible.

docs: enhance usage of video carrousel

---

_data/icons.yml
_data/icons_builder.yml

@kennydee found out that link in footer were not working and targetting correct account
- change github to the blog repository
- define twitter to the Bedrock_tech account
- define linkedin to the official page

fix: social links in footer

---

pages/meetup-conference.md

@kennydee Asked me if it was possible to add somewhere on the blog the list of talks given by bedrock employee.
Here it is.
I just added 2022 event I have been aware of.
I will ask for contributions for past events.

feat: start the list of conferences

---

.github/workflows/integration.yml

Previously, deploy workflow was the default one of Github page.
But, this workflow is different as the used one for dev and in continuous integration testing, especially on the Jekyll version used.
With this PR, the deploy workflow will use the static site builded in the "Build" step, and will use same process than the development process.

GHA workflow to deploy, to use same workflow than dev one

---

CONTRIBUTING.md

Some links to the theme's author blog are broken in the _How to add an article to the blog?_ part
Current links instead.

Fix broken links for theme documentation

---

_sass/base/_global.scss
_sass/base/_variables.scss

When I follow bedrock assets style in the PR #304, I was asked to put all the titles in uppercase.
At first this could be a good idea.
Using capslock heading are really bad for people to read.
[You can read more about that in this article](https://readabilityguidelines.co.uk/grammar-points/capital-letters/)
- drop uppercase style on headings 
- use different color in h3 -> h6 in order to help readers understand that the level changed

feat: change heading style for reading purpose

---

_posts/2022-08-12-backend-fallbacks.md

Fixing a mistake in the last blog post about the BFF stale cache usage.

fix: update usage of stale cache headers with more information

---

pages/about.md

About page is so empty, why not removing it ?

feat: remove about page

---

_posts/2022-09-01-kubernetes-prescaling-we-open-source-our-solution.md

A link in the article "Prescaling pods in Kubernetes, we open source our solution" is not interpreted.

fix: non-interpreted link

---

_includes/blog/blog.liquid
_posts/2022-11-15-onboarding-revue-code.md

Les extraits d'articles, sur la page d'accueil du blog, sont *moches*.
Voici les deux derniers, aujourd'hui :
Je me dis que ça rendrait bien mieux si on conservait le HTML. Les paragraphes, notamment. Mais aussi les liens (il y en a dans l'excerpt d'un article plus bas).
Sur les deux mêmes articles, ça donnerait ceci (screenshoté depuis mon poste, mais la preview devrait bientôt arriver ;-)) :
Je suis remonté sur quelques (seulement quelques unes, j'avoue) pages d'historique, ça me semble mieux "maintenant" que "avant"… Qu'en pensez-vous ?

Keep HTML in excerpts on homepage

---

_includes/blog/blog.liquid
_includes/blog/post_info.liquid
_sass/layouts/_posts.scss

We want to have a liste of authors whenever multiple persons publish an article.
The first commit make sure multiple authors appears: 
- with my PR :
- vs before:
The second commit make them appear inline rather than weirdly : 
- looks nice : 
- looks bad :
Thanks for the reviews :+1:

fix(template): fix multiple authors not showing up
