_posts/2015-05-07-m6web-dev-facts-7.md

Comme ça fait longtemps, un nouveau dev facts.
Je propose d'attendre jeudi pour le publier, pour ne pas publier trop de choses en même temps (cf. #94)

Dev Facts #7

---

_posts/2015-05-07-m6web-dev-facts-8.md
_posts/2015-11-06-m6web-dev-facts-9.md

DevFacts #9

---

_posts/2015-11-27-beta-nouveau-6play-backend.md

Pour relecture
ping @kennydee @omansour @fabdsp

Blog post about 6play backend

---

_config.yml

See https://github.com/jekyll/jekyll/issues/4440

Add trailing slash (removed by jekyll 3 ...)

---

oss.md

Add link to [SeyrenLight](https://github.com/M6Web/SeyrenLight) github repo in OSS page

Add SeyrenLight in OSS page

---

oss.md

* Sey**R**en
* Added a link to Seyren project

Fixed a typo in oss.md

---

.travis.yml
_config.yml
_includes/head.html
index.html
package.json

Permet d'avoir un espace de recette sur http://techm6webfr.surge.sh/ pour le moment

Add surge support

---

_posts/2016-06-23-video-phptour-worker-php.md

conf de fdsp au phptour

---

_posts/2016-11-24-une-donnee-presque-parfaite.md

L'URL du fichier PDF ne fonctionne pas actuellement : cette PR corrige le lien.
Merci pour le partage ;)

Fix the URL of the PDF file.

---

_posts/2017-02-20-retour-de-paris-video-tech.md

to my mind Mozilla is a better reference on Javascript

Change W3schools reference to Mozilla

---

oss.md

add RedisMessageBrocker

---

404.md
_config.yml
oss.md

GH now provide LE certificate https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ 
let's go !

switch to https everywhere

---

_posts/2018-05-21-kubecon-2018-copenhaguen-day-1.md

file was fixed in previous commit but not filename in post

fix bad filename

---

_posts/2018-05-23-kubecon-2018-copenhaguen-day-3.md

After [the post for day 1](https://tech.m6web.fr/kubecon-2018-copenhaguen-day-1/) and the [PR for day 2](https://github.com/M6Web/m6web.github.io/pull/193), here's the post for day 3 ;-)
It has already been reviewed by a few people on https://github.com/M6Web/m6web.github.io/pull/190

Kubecon 2018: day 3

---

_posts/2018-05-24-kubecon-2018-copenhaguen-global-review.md

From the last post, add links to the other 3.

Add links to the 3 other posts

---

_posts/2018-05-24-kubecon-2018-copenhaguen-global-review.md

Fix link... sorry.

---

_posts/2020-02-07-pascal-martin-laduckconf.md

pascal à la duck conf

---

about.md

Change M6Web mentions to Bedrock.

Update About page for Bedrock

---

jobs.md

Will see later if i can directly link the menu to the jobs page from the corporate website.

Update jobs page for bedrock

---

oss.md

Change M6Web mention to Bedrock

Update Oss page with Bedrock instead of M6Web

---

oss.md

Add [Tornado](https://github.com/M6Web/Tornado) link in OSS libs 
🌪️ 🏇

feat(oss): add Tornado library link

---

_posts/2019-03-11-Migrating-production-apps-from-on-premise-to-the-cloud-with-no-downtime.md

As the main part of the talk explains what's said in this blogpost, it's
interesting to share this.

feat(2019-03-11): Add Youtube embed video

---

index.html

Fix m6web to bedrock

---

_posts/2021-09-06-web-best-practices.md

- share translation of the last published article from https://slashgear.github.io/how-not-to-throw-away-your-web-application-after-two-years/

feat(post): publish translation of a post

---

_posts/2021-10-18-increase-performance-and-stability-by-adding-an-egress-controller.md

fix(post/typo): egress

---

_posts/2021-10-18-increase-performance-and-stability-by-adding-an-egress-controller.md

fix typo on haproxy-egress

---

_config.yml
_layouts/post.html

remove obsolete third party

---

_data/authors.yml
_posts/2022-02-27-streaming-recommendation.md

Fix post after changes in the template.

Fix(post): streaming recommendation

---

_posts/2022-04-20-aws-summit-2022-notre-retour-dexperience.md

Fixing little spelling mistake in blog post

fix(post): replace au aws summit by a l aws summit

---

_posts/2022-06-13-kubecon-2022-part-1.md

fix: remove figure element

---

_posts/2022-04-21-vite-the-webpack-killer.md
_posts/2022-06-08-comment-ne-pas-jeter-votre-application.md

Add a bunch of my talk to public events (Devoxx and LyonJS) with @fdubost and Mathieu Mure.

feat: add talk with a_caron and friends

---

_posts/2018-11-14-docker-en-prod-oui-avec-kubernetes-pascal-martin.md
_posts/2019-11-25-une-application-resiliente-dans-un-monde-partiellement-degrade-pascal-martin.md
_posts/2020-11-18-php-cest-vous-et-vous-pouvez-contribuer-pascal-martin.md
_posts/2021-04-02-migration-6play-vers-le-cloud-retour-experience-pascal-martin.md
_posts/2021-04-06-comment-nous-reduisons-augmentation-couts-aws-pascal-martin.md
_posts/2021-07-27-no-code-developpement-applications-ouvert-autres-metiers-pascal-martin.md

Quelques unes de mes confs ; le plus gros de celles que j'ai faites depuis que je suis chez M6 Web / Bedrock, en ne mettant pas trop de duplicates.
Preview : https://add-pmartin-talks.dsvmt7xpjktgx.amplifyapp.com/meetups/

Quelques talks de P. Martin

---

_data/authors.yml
_posts/2020-10-23-l'open-source-ce-n-est-pas-que-pour-le-web.md

Add a talk given by me during the Forum PHP about Open source

feat: add a talk about Open Source, forum PHP 2020

---

_posts/2016-04-24-arretons-de-perdre-du-temps.md
_posts/2019-01-14-7-conseils-pour-demarrer-avec-spark.md
_posts/2019-11-14-machine-learning-sans-magie-et-sans-sarracher-les-cheveux.md
_posts/2020-02-10-apache-spark-et-le-machine-learning-reves-et-realites.md
_posts/2021-01-21-machine-learning-en-production.md
_posts/2021-05-25-productionizing-ml-systems-without-fear-nor-heroism.md

feat: add talks for Nastasia Saby

---

.github/workflows/deployment.yml
.github/workflows/integration.yml

feat(gha): separate CI and CD workflows

---

README.md

Badges of workflow were not updated since the new deployment process
- change url of badges
- add new fun badges

docs(readme): udpate badges

---

_data/authors.yml
_posts/2022-06-03-amateur-de-pression.md
_posts/2022-06-03-comment-faire-un-trailer-video-qui-dechire-avec-les-technos-web.md
_posts/2022-06-03-connaissez-vous-cache°cache.md
_posts/2022-06-03-creer-un-jeu-video-en-moins-dune-heure-sur-unity.md
_posts/2022-06-03-errances-a-kiilopaala.md
_posts/2022-06-03-la-pression-je-ne-la-subis-pas-je-la-fais.md
_posts/2022-06-03-🍪-its-cookie-jar-time-🍪.md

👋🏻 Here is a small PR adding June 2022 videos of the LFT.
- add 7 new post
- No Author on those article, I don't really know if I should put author on each article. Let me know.

feat: add june 2022 LFT videos

---

_config.yml
_includes/default/head.liquid

We want to get statistics on our tech blog and can't use Google Analytics for that.
I created a Matomo account and website and added script in `<head>`.

feat(tracking): setup matomo tracking method

---

_includes/default/head.liquid

Migrating to an other Matomo account.
Updating script config to match new account.

feat(tracking): update matomo script config

---

_config.yml
_data/icons.yml
_includes/default/head.liquid

We want to have a link to Youtube an 10 posts per page.
Adding Youtube ID and increasing posts amount per page.

feat(tech-blog): show more posts, add youtube link and fmt

---

_posts/2022-09-06-monitoring-at-scale-with-victoriametrics.md

consideration of pascal and christian's observations in the previous PR

fix: syntax and duplicate entrie

---

_posts/2022-10-13-bff-notre-best-friend-forever-pour-faire-plein-d-applications-frontend.md
_posts/2022-10-13-comprenez-comment-php-fonctionne-vos-applications-marcheront-mieux.md
_posts/2022-10-13-revue-de-code-on-n-est-pas-venu-pour-souffrir.md
_posts/2022-10-13-sauve-une-dev-ecris-une-doc.md

Ajout des 4 conférences données par des intervents Bedrock au Forum PHP 2022.

Forum php 2022: add conferences

---

_data/authors.yml
_posts/2022-11-25-docteur-qui.md
_posts/2022-11-25-ecrire-un-livre-mais-pourquoi-faire.md
_posts/2022-11-25-fabriquer-sa-table-avec-plateau-live-edge-tout-ce-quil-faut-faire-ou-pas.md
_posts/2022-11-25-quarante-min-pour-comprendre-informatique-quantique.md
_posts/2022-11-25-reconstitution-medieval.md
_posts/2022-11-25-to-be-or-not-to-be.md
_posts/2022-11-25-trois-patterns-avances-pour-ameliorer-la-resilience-une-application.md
_posts/2022-11-25-trophy-hunter.md

- add [Last Friday Talks](https://www.youtube.com/watch?v=52JEUdJk2BY&list=PLnDWTaF0FDIsgwsd5NWzp1wx4L9OeUoc9) from November 2022
- use PascalCase for all authors (for visual consistency in the Last Friday Talks page)

feat(lft): add talks from LFT November 2022

---

Gemfile.lock
_data/authors.yml
_data/conferences.yaml

Add 2 missing conferences : 
* Pascal Martin at MiXiT 2023
* Pauline Rambaud at AFUP Day Lyon 2023

Add MiXiT 2023 and AFUP Day Lyon 2023 speakers

---

_data/authors.yml
_posts/2023-09-29-json-au-service-des-devs.md
_posts/2023-09-29-la-traversee-du-finnmarksvidda-carnet-de-bord-d-une-aventure-glaciale.md
_posts/2023-09-29-le-don-du-sang.md
_posts/2023-09-29-mentors-super-heros-ou-super-vilains.md
_posts/2023-09-29-nourrir-nos-ia.md
_posts/2023-09-29-siteswap-jongler-avec-les-maths.md

feat(lft): add LFTs for September 2023

---

.devcontainer/devcontainer.json
.vscode/tasks.json
_data/authors.yml
_posts/2023-11-24-comment-faire-de-votre-vie-un-blackfriday-permanent.md
_posts/2023-11-24-comment-ne-pas-jeter-son-application-frontend-tout-les-deux-ans.md
_posts/2023-11-24-jeux-video-websocket-et-binaire-temps-reel-efficace-pour-navigateur.md
_posts/2023-11-24-le-futur-du-web-est-sur-la-peripherie-du-reseau.md
_posts/2023-11-24-stop-a-l-espionnage-comment-disparaitre-d-internet.md

- add LFTs for November 2023
- fix dev env for VSCode 
- use port 35728 instead of 8080 which is already heavily used by web developers
- update deprecated keys (settings, extensions)

feat(lft): add LFTs for November 2023

---

_posts/2013-05-06-la-poo-canada-dry.md
_posts/2013-05-22-redis-on-fire.md
_posts/2013-06-26-encodage-packaging-drm-tout-sur-la-video.md
_posts/2013-07-19-introduction-a-drupal-par-claire-roubey-clever-age.md
_posts/2013-10-08-le-nosql-focus-sur-mongodb-par-cedric-derue-altran.md
_posts/2014-01-18-vagrant-julien-bianchi.md
_posts/2015-04-01-immutablejs-relay-graphql-react-native.md

- remove broken LFT videos from LFT page

fix(lft): remove broken LFT videos

---

_posts/2023-11-14-swift-concurrency-in-a-nutshell.md

Correcting inaccurate information regarding function execution

---

_data/conferences.yaml
_posts/2024-04-17-sauve-un-e-dev-ecris-une-doc.md

* Blog post with video replay
* Added to the conference list

Add devoxx 2024 s_haim

---

_data/conferences.yaml
_posts/2023-06-19-ameliorons-ensemble-la-doc-de-postgresql

* updated conferences.yaml
* adding 1 video replay as a blogpost

Add postgres talks by s_haim
